import { FiCalendar, FiCheckCircle, FiUser } from 'react-icons/fi'
import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'
import SectionHeading from '../components/SectionHeading'
import usePageMeta from '../hooks/usePageMeta'
import { sellers } from '../data/sellers'

const Sellers = () => { usePageMeta({ title: 'Property Sellers and Guides | D&C Prime Realty', description: 'Review the frontend property-guide options for the current Bailen and Maragondon projects.' }); return <><PageHero eyebrow="Sellers" title="Choose a property guide for your visit" description="The public team directory will help clients select a preferred seller or guide when requesting a property tripping." image="/website/images/company/office-team-collage.jpg" /><section className="px-5 py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-[1300px]"><SectionHeading eyebrow="Frontend directory" title="Property guidance team" description="The current entries are design placeholders. Public seller profiles can be connected to approved data later without exposing private system information." /><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{sellers.map((seller) => <article key={seller.id} className="rounded-[24px] border border-[#e6dbc2] bg-white p-7 shadow-[0_18px_55px_rgba(93,69,14,0.07)]"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff0ba] text-[#9d7007]"><FiUser className="h-7 w-7" /></span><p className="mt-6 text-[11px] font-black uppercase tracking-[0.15em] text-[#9d7007]">{seller.position}</p><h2 className="mt-2 text-[22px] font-black tracking-[-0.03em]">{seller.name}</h2><p className="mt-2 flex items-center gap-2 text-[13px] font-bold text-[#4d6b4c]"><FiCheckCircle /> {seller.project}</p><p className="mt-4 text-[13px] leading-6 text-[#6b6251]">{seller.description}</p><Link to="/properties#book-tripping" className="mt-6 inline-flex items-center gap-2 text-[13px] font-black text-[#76550c]"><FiCalendar /> Choose for tripping</Link></article>)}</div></div></section></> }
export default Sellers
