import { useState } from 'react'
import { FiCreditCard, FiPlus, FiSearch } from 'react-icons/fi'
import PageHeader from '../../components/Shared/PageHeader'
import StatusAlert from '../../components/Shared/StatusAlert'
import AddPaymentModal from '../../components/BailenProject/PaymentComponents/AddPaymentModal/AddPaymentModal'
const money = (value) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(Number(value || 0))
const clientUnits=[{unitCode:'LA-0402', buyer:'Robert San Juan', tcp:1008000, balance:839200, status:'Active'},{unitCode:'LA-0501', buyer:'Nico Reyes', tcp:772200, balance:0, status:'Fully Paid'},{unitCode:'LA-0502', buyer:'Mika Fernandez', tcp:881280, balance:771280, status:'Pending Cancellation'}]
const Payment = () => { const [showAdd,setShowAdd]=useState(false); const [selected,setSelected]=useState(clientUnits[0]); const [alert,setAlert]=useState(null); return <main className="flex flex-col gap-6"><section className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><PageHeader title="Bailen Payments" description="Mock payment input. Admin-entered payments are treated as verified." icon={FiCreditCard}/><button onClick={()=>setShowAdd(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 text-sm font-black text-white"><FiPlus />Add Payment</button></section>{alert ? <StatusAlert type={alert.type} message={alert.message} onClose={()=>setAlert(null)} /> : null}<section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">Client Units</h2><p className="text-sm font-semibold text-slate-500">Select a mock account before adding payment.</p></div><label className="relative"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input placeholder="Search account..." className="h-11 rounded-2xl border border-slate-200 pl-11 pr-3 text-sm font-semibold"/></label></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{clientUnits.map(unit=><button key={unit.unitCode} onClick={()=>setSelected(unit)} className={`rounded-3xl border p-5 text-left transition ${selected.unitCode===unit.unitCode?'border-blue-200 bg-blue-50':'border-slate-200 bg-white hover:bg-slate-50'}`}><p className="font-black text-slate-950">{unit.unitCode}</p><p className="mt-1 text-sm font-semibold text-slate-500">{unit.buyer}</p><p className="mt-4 text-xs font-black uppercase text-slate-400">Balance</p><p className="text-xl font-black text-slate-950">{money(unit.balance)}</p><span className="mt-3 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-700">{unit.status}</span></button>)}</div></section>{showAdd ? <AddPaymentModal listing={{unitCode:selected.unitCode,tcp:selected.balance}} onClose={()=>setShowAdd(false)} onSave={()=>{setShowAdd(false); setAlert({type:'success',message:'Mock payment saved as verified.'})}} /> : null}</main> }
export default Payment
