import { PERMISSIONS, getAuditorEnforcedPermissions } from './permissions.js';

// Product-recommended starting templates. These are intentionally separate from
// persisted role_permission_defaults: Super Admin may edit the persisted defaults,
// while this map remains the explicit "Reset to recommended defaults" baseline.
const BASE_ROLE_PERMISSIONS = Object.freeze({
  system_admin: Object.freeze([
    // System Admin is governance + case-driven correction, not a routine operations super-user.
    PERMISSIONS.SYSTEM_DASHBOARD_VIEW, PERMISSIONS.SYSTEM_REPORTS_VIEW,
    PERMISSIONS.SYSTEM_PROJECTS_VIEW, PERMISSIONS.SYSTEM_PROJECTS_PRINT_PRICE_LIST,
    PERMISSIONS.SYSTEM_USERS_VIEW, PERMISSIONS.SYSTEM_USERS_CREATE, PERMISSIONS.SYSTEM_USERS_EDIT, PERMISSIONS.SYSTEM_USERS_RESET_PASSWORD, PERMISSIONS.SYSTEM_USERS_DEACTIVATE,
    PERMISSIONS.SYSTEM_ACCREDITED_VIEW, PERMISSIONS.SYSTEM_SELLER_GROUPS_VIEW,
    PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.EMPLOYMENT_HISTORY_VIEW, PERMISSIONS.EMPLOYEE_SALARY_VIEW, PERMISSIONS.PAYROLL_HISTORY_VIEW, PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW, PERMISSIONS.SYSTEM_DATA_INTEGRITY_VIEW, PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW,
    PERMISSIONS.SYSTEM_DOCUMENTS_VIEW, PERMISSIONS.SYSTEM_DOCUMENT_TEMPLATES_VIEW,
    PERMISSIONS.SYSTEM_SETTINGS_VIEW,
    PERMISSIONS.LOT_PROJECT_VIEW, PERMISSIONS.LOT_DASHBOARD_VIEW, PERMISSIONS.LOT_REPORTS_VIEW,
    PERMISSIONS.LOT_LISTINGS_VIEW, PERMISSIONS.LOT_LISTING_PROFILE_VIEW,
    PERMISSIONS.LOT_PAYMENTS_VIEW, PERMISSIONS.LOT_BUYER_DOCUMENTS_VIEW, PERMISSIONS.LOT_ACCOUNT_HISTORY_VIEW, PERMISSIONS.LOT_PAYMENT_LOGS_VIEW,
    PERMISSIONS.LOT_COMMISSIONS_VIEW, PERMISSIONS.LOT_SETTINGS_VIEW, PERMISSIONS.LOT_SETTINGS_MANAGE,
    // These write keys only open controlled correction endpoints; controllers still require a valid Auditor-approved case.
    PERMISSIONS.LOT_LISTINGS_EDIT, PERMISSIONS.LOT_BUYER_DOCUMENTS_UPDATE, PERMISSIONS.LOT_PAYMENTS_EDIT, PERMISSIONS.LOT_PAYMENT_DELETE, PERMISSIONS.LOT_RESERVATION_CORRECT, PERMISSIONS.LOT_BUYER_PROFILE_EDIT, PERMISSIONS.LOT_COMMISSIONS_ADJUST, PERMISSIONS.LOT_PENALTY_CORRECT,
  ]),
  marketing_staff: Object.freeze([
    PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
    PERMISSIONS.SYSTEM_DASHBOARD_VIEW, PERMISSIONS.SYSTEM_REPORTS_VIEW,
    PERMISSIONS.SYSTEM_PROJECTS_VIEW, PERMISSIONS.SYSTEM_PROJECTS_PRINT_PRICE_LIST,
    PERMISSIONS.SYSTEM_ACCREDITED_VIEW, PERMISSIONS.SYSTEM_SELLER_GROUPS_VIEW, PERMISSIONS.SYSTEM_SELLER_GROUPS_MANAGE,
    PERMISSIONS.SYSTEM_USERS_CREATE, PERMISSIONS.SYSTEM_USERS_EDIT,
    PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW, PERMISSIONS.SYSTEM_DOCUMENTS_VIEW,
    PERMISSIONS.LOT_PROJECT_VIEW, PERMISSIONS.LOT_DASHBOARD_VIEW, PERMISSIONS.LOT_REPORTS_VIEW, PERMISSIONS.LOT_LISTINGS_VIEW,
  ]),
  sales_staff: Object.freeze([
    PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
    PERMISSIONS.SYSTEM_DASHBOARD_VIEW, PERMISSIONS.SYSTEM_REPORTS_VIEW,
    PERMISSIONS.SYSTEM_PROJECTS_VIEW, PERMISSIONS.SYSTEM_PROJECTS_PRINT_PRICE_LIST,
    PERMISSIONS.SYSTEM_ACCREDITED_VIEW, PERMISSIONS.SYSTEM_ACCREDITED_PRINT, PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW, PERMISSIONS.SYSTEM_DOCUMENTS_VIEW,
    PERMISSIONS.LOT_PROJECT_VIEW, PERMISSIONS.LOT_DASHBOARD_VIEW, PERMISSIONS.LOT_REPORTS_VIEW,
    PERMISSIONS.LOT_LISTINGS_VIEW, PERMISSIONS.LOT_LISTING_PROFILE_VIEW, PERMISSIONS.LOT_RESERVATIONS_CREATE, PERMISSIONS.LOT_RESERVATION_CORRECT,
    PERMISSIONS.LOT_BUYER_PROFILE_EDIT, PERMISSIONS.LOT_BUYER_DOCUMENTS_VIEW, PERMISSIONS.LOT_BUYER_DOCUMENTS_UPDATE,
    PERMISSIONS.LOT_ACCOUNT_HISTORY_VIEW, PERMISSIONS.LOT_PRINTOUTS_USE, PERMISSIONS.LOT_COMMISSIONS_VIEW,
  ]),
  accounting_staff: Object.freeze([
    PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
    PERMISSIONS.SYSTEM_DASHBOARD_VIEW, PERMISSIONS.SYSTEM_REPORTS_VIEW, PERMISSIONS.SYSTEM_REPORTS_EXPORT,
    PERMISSIONS.SYSTEM_PROJECTS_VIEW, PERMISSIONS.SYSTEM_PROJECTS_PRINT_PRICE_LIST,
    PERMISSIONS.SYSTEM_ACCREDITED_VIEW, PERMISSIONS.SYSTEM_ACCREDITED_PRINT, PERMISSIONS.SYSTEM_ACCREDITED_UPLOAD_PROOF,
    PERMISSIONS.EMPLOYMENT_HISTORY_VIEW,
    PERMISSIONS.EMPLOYEE_SALARY_VIEW, PERMISSIONS.PAYROLL_GENERATE, PERMISSIONS.PAYROLL_RECALCULATE_DRAFT, PERMISSIONS.PAYROLL_FINALIZE, PERMISSIONS.PAYROLL_CORRECT_FINALIZED, PERMISSIONS.PAYROLL_RELEASE, PERMISSIONS.PAYROLL_HISTORY_VIEW, PERMISSIONS.PAYROLL_RECEIPT_PRINT, PERMISSIONS.PAYROLL_RECEIPT_EXPORT, PERMISSIONS.PAYROLL_SETTINGS_MANAGE, PERMISSIONS.PAYROLL_SUMMARY_EXPORT,
    PERMISSIONS.AUDIT_LOGS_VIEW, PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW, PERMISSIONS.SYSTEM_DOCUMENTS_VIEW,
    PERMISSIONS.LOT_PROJECT_VIEW, PERMISSIONS.LOT_DASHBOARD_VIEW, PERMISSIONS.LOT_REPORTS_VIEW, PERMISSIONS.LOT_REPORTS_EXPORT,
    PERMISSIONS.LOT_LISTINGS_VIEW, PERMISSIONS.LOT_LISTING_PROFILE_VIEW,
    PERMISSIONS.LOT_PAYMENTS_VIEW, PERMISSIONS.LOT_PAYMENTS_CREATE, PERMISSIONS.LOT_PAYMENTS_EDIT, PERMISSIONS.LOT_PAYMENT_DELETE,
    PERMISSIONS.LOT_BUYER_DOCUMENTS_VIEW, PERMISSIONS.LOT_ACCOUNT_HISTORY_VIEW, PERMISSIONS.LOT_PRINTOUTS_USE, PERMISSIONS.LOT_PAYMENT_LOGS_VIEW,
    PERMISSIONS.LOT_COMMISSIONS_VIEW, PERMISSIONS.LOT_COMMISSIONS_ADJUST, PERMISSIONS.LOT_COMMISSIONS_RELEASE, PERMISSIONS.LOT_COMMISSIONS_HOLD, PERMISSIONS.LOT_COMMISSIONS_UNHOLD, PERMISSIONS.LOT_PENALTY_CORRECT,
  ]),
  operations_staff: Object.freeze([
    PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
    PERMISSIONS.SYSTEM_DASHBOARD_VIEW, PERMISSIONS.SYSTEM_REPORTS_VIEW, PERMISSIONS.SYSTEM_REPORTS_EXPORT,
    PERMISSIONS.SYSTEM_PROJECTS_VIEW, PERMISSIONS.SYSTEM_PROJECTS_CREATE, PERMISSIONS.SYSTEM_PROJECTS_EDIT, PERMISSIONS.SYSTEM_PROJECTS_PRINT_PRICE_LIST,
    PERMISSIONS.SYSTEM_USERS_VIEW, PERMISSIONS.SYSTEM_ACCREDITED_VIEW,
    PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.EMPLOYEES_MANAGE,
    PERMISSIONS.EMPLOYEE_COMPENSATION_MANAGE, PERMISSIONS.EMPLOYMENT_CHANGE_CREATE, PERMISSIONS.EMPLOYMENT_HISTORY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.AUDIT_LOGS_VIEW, PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW, PERMISSIONS.SYSTEM_NOTIFICATIONS_MANAGE,
    PERMISSIONS.SYSTEM_DOCUMENTS_VIEW, PERMISSIONS.SYSTEM_DOCUMENTS_CREATE, PERMISSIONS.SYSTEM_DOCUMENTS_EDIT, PERMISSIONS.SYSTEM_DOCUMENTS_DELETE,
    PERMISSIONS.SYSTEM_DOCUMENT_TEMPLATES_VIEW, PERMISSIONS.SYSTEM_DOCUMENT_TEMPLATES_CREATE, PERMISSIONS.SYSTEM_DOCUMENT_TEMPLATES_EDIT, PERMISSIONS.SYSTEM_DOCUMENT_TEMPLATES_DELETE,
    PERMISSIONS.LOT_PROJECT_VIEW, PERMISSIONS.LOT_DASHBOARD_VIEW, PERMISSIONS.LOT_REPORTS_VIEW,
    PERMISSIONS.LOT_LISTINGS_VIEW, PERMISSIONS.LOT_LISTINGS_IMPORT, PERMISSIONS.LOT_LISTINGS_CREATE, PERMISSIONS.LOT_LISTINGS_EDIT, PERMISSIONS.LOT_LISTINGS_DELETE, PERMISSIONS.LOT_LISTING_PROFILE_VIEW, PERMISSIONS.LOT_RESERVATIONS_CREATE,
    PERMISSIONS.LOT_BUYER_PROFILE_EDIT, PERMISSIONS.LOT_BUYER_DOCUMENTS_VIEW, PERMISSIONS.LOT_BUYER_DOCUMENTS_UPDATE,
    PERMISSIONS.LOT_ACCOUNT_HISTORY_VIEW, PERMISSIONS.LOT_PRINTOUTS_USE, PERMISSIONS.LOT_PAYMENT_LOGS_VIEW, PERMISSIONS.LOT_COMMISSIONS_VIEW,
    PERMISSIONS.LOT_SETTINGS_VIEW, PERMISSIONS.LOT_SETTINGS_MANAGE,
  ]),
});

const headExtras = Object.freeze([
  PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
  PERMISSIONS.WORKFLOW_DEPARTMENT_REVIEW,
  PERMISSIONS.WORKFLOW_DEPARTMENT_RETURN_FOR_CORRECTION,
  PERMISSIONS.WORKFLOW_DEPARTMENT_APPROVE_PROTECTED_CHANGE,
  PERMISSIONS.WORKFLOW_DEPARTMENT_CASE_RESPOND,
]);

const systemAdminExtras = Object.freeze([
  PERMISSIONS.SYSTEM_ACCESS_CONTROL_VIEW,
  PERMISSIONS.SYSTEM_ACCESS_CONTROL_MANAGE,
  PERMISSIONS.WORKFLOW_REVIEW_CENTER_VIEW,
  PERMISSIONS.WORKFLOW_SYSTEM_CORRECTION_APPLY,
]);

export const RECOMMENDED_ROLE_PERMISSIONS = Object.freeze({
  ...BASE_ROLE_PERMISSIONS,
  marketing_staff: BASE_ROLE_PERMISSIONS.marketing_staff,
  sales_staff: BASE_ROLE_PERMISSIONS.sales_staff,
  accounting_staff: BASE_ROLE_PERMISSIONS.accounting_staff,
  operations_staff: BASE_ROLE_PERMISSIONS.operations_staff,
  system_admin: Object.freeze([...new Set([
    ...(BASE_ROLE_PERMISSIONS.system_admin || []),
    ...systemAdminExtras,
  ])]),
  auditor: Object.freeze(getAuditorEnforcedPermissions()),
  marketing_head: Object.freeze([...new Set([...(BASE_ROLE_PERMISSIONS.marketing_staff || []), ...headExtras])]),
  sales_head: Object.freeze([...new Set([...(BASE_ROLE_PERMISSIONS.sales_staff || []), ...headExtras])]),
  accounting_head: Object.freeze([...new Set([...(BASE_ROLE_PERMISSIONS.accounting_staff || []), ...headExtras])]),
  operations_head: Object.freeze([...new Set([...(BASE_ROLE_PERMISSIONS.operations_staff || []), ...headExtras])]),
});
