import type { Bailen_Lot_Listing } from "../../types/listing";
import type { BailenPaymentRecord, BailenSOARow } from "../../types/payment";
import type { Commission } from "../../types/commission";

const createPrimaryBuyer = (fullName: string) => ({
  full_name: fullName,
  email: `${fullName.toLowerCase().replaceAll(" ", ".")}@gmail.com`,
  contact_no: "09XXXXXXXXX",
  residence_contact_no: "046-000-0000",
  birth_date: "1998-01-01",
  place_of_birth: "Cavite",
  citizenship: "Filipino",
  gender: "male" as const,
  civil_status: "Single" as const,
  tin: "000-000-000-000",
  valid_id_type: "Passport",
  valid_id_no: "P0000000A",
  present_address: "Indang, Cavite",
  present_zip_code: "4122",
  permanent_address: "Indang, Cavite",
  permanent_zip_code: "4122",
  employment_status: "Employed - Private" as const,
  employer_or_business_name: "Sample Employer Inc.",
  position_or_business_type: "Employee",
  work_address: "Cavite",
  monthly_income: 35000,
  source_of_funds: "Salary",
});

export const createBailenListing = (
  id: number,
  unitCode: string,
  status: Bailen_Lot_Listing["bailen_lot_listing_status"],
  area: number,
  pricePerSqm: number,
  buyerName: string | null,
  sellerName: string | null
): Bailen_Lot_Listing => {
  const netSellingPrice = area * pricePerSqm;
  const legalMiscRate = 10;
  const lmf = netSellingPrice * (legalMiscRate / 100);
  const tcp = netSellingPrice + lmf;
  const cadastralId = id <= 4 ? id : ((id - 1) % 4) + 1;

  return {
    bailen_lot_listing_id: id,
    client_id: buyerName ? id : null,
    accredited_seller_id: sellerName ? id : null,
    bailen_lot_listing_project_id: 1,
    bailen_lot_listing_unit_id: Number(unitCode.replace("LA-", "")),
    bailen_lot_listing_unit_code: unitCode,
    bailen_lot_listing_old_unit_ids: id === 1 ? ["LA-0204", "LA-0202"] : [],
    bailen_lot_listing_cadastral_lot_number_ids: [cadastralId],
    bailen_lot_listing_cadastral_lot_numbers: [`CAD-00${cadastralId}`],
    bailen_lot_listing_lot_type:
      id % 3 === 0 ? "corner" : id % 2 === 0 ? "end" : "inner",
    bailen_lot_listing_reservation_fee: 50000,
    bailen_lot_listing_price_sqm: pricePerSqm,
    bailen_lot_listing_lot_area_sqm: area,
    bailen_lot_listing_lot_are_sqm: area,
    bailen_lot_listing_legal_misc_rate: legalMiscRate,
    bailen_lot_listing_annual_interest_rate: 7.5,
    bailen_lot_listing_net_selling_price: netSellingPrice,
    bailen_lot_listing_legal_misc_fee: lmf,
    bailen_lot_listing_total_contract_price: tcp,
    bailen_lot_listing_status: status,
    bailen_lot_listing_documents: [
      {
        document_id: 1,
        document_name: "CLIENT REGISTRATION FORM (Seller's Copy)",
        document_description: "Required buyer registration form.",
        document_is_reusable: 1,
        document_status: "active",
        document_is_required: 1,
        document_created_at: "2026-06-29",
        document_updated_at: "2026-06-29",
        upload_status: status === "sold" ? "submitted" : "not_available",
        uploaded_file_name: status === "sold" ? "client-registration.pdf" : null,
        uploaded_at: status === "sold" ? "2026-07-01" : null,
        reviewed_by: status === "sold" ? "Admin" : null,
        remarks: status === "sold" ? "For review." : "Upload available after sold.",
      },
      {
        document_id: 3,
        document_name: "OFFER TO BUY & BUYER'S PROFILE",
        document_description: "Generated printout after client profile completion.",
        document_is_reusable: 1,
        document_status: "active",
        document_is_required: 1,
        document_created_at: "2026-06-29",
        document_updated_at: "2026-06-29",
        upload_status: status === "sold" ? "missing" : "not_available",
        uploaded_file_name: null,
        uploaded_at: null,
        reviewed_by: null,
        remarks: status === "sold" ? "Pending signed copy." : "Upload available after sold.",
      },
    ],
    bailen_lot_listing_client_profile: buyerName
      ? {
          client_profile_id: id,
          client_id: id,
          buyer_type: "single",
          primary_buyer: createPrimaryBuyer(buyerName),
          second_buyer: null,
          emergency_contact_name: "Emergency Contact",
          emergency_contact_no: "09170000000",
          emergency_contact_relationship: "Sibling",
          profile_status: "complete",
          saved_at: "2026-07-01",
        }
      : null,
    bailen_lot_listing_payment_terms: buyerName
      ? {
          payment_mode: "installment",
          term_months: 36,
          first_due_date: "2026-07-22",
          due_day: 22,
          reservation_paid: true,
          reservation_date: "2026-07-01",
          downpayment_percent: 30,
          downpayment_months: 3,
          monthly_amortization: 35900,
          balloon_payment: 0,
          balance: tcp - 50000,
          remarks: "Sample terms for design only.",
        }
      : null,
    bailen_lot_listing_commission_snapshot: sellerName
      ? {
          seller_name: sellerName,
          seller_group_name: "SARTE, JOHN CHRISTOPHER GROUP",
          seller_rate_bailen: 3,
          commission_pool_rate_bailen: 12,
          commission_status: "pending",
        }
      : null,
    bailen_lot_listing_created_at: "2026-07-01",
    bailen_lot_listing_updated_at: "2026-07-01",
  };
};

export const sampleBailenListings: Bailen_Lot_Listing[] = [
  createBailenListing(1, "LA-0203", "available", 1000, 555, null, null),
  createBailenListing(2, "LA-0204", "reserved", 900, 560, "Robert San Juan", "CANTIGA, ROLINDA C."),
  createBailenListing(3, "LA-0205", "sold", 850, 575, "Juan Dela Cruz", "PARROCHO, JOSEPH E."),
  createBailenListing(4, "LA-0206", "hold", 760, 590, null, "REYES, MARIA L."),
  createBailenListing(5, "LA-0207", "pending for cancellation", 820, 575, "Maria Santos", "CANTIGA, ROLINDA C."),
  createBailenListing(6, "LA-0208", "cancelled", 800, 550, null, null),
];

export const sampleBailenPayments: BailenPaymentRecord[] = [
  {
    payment_id: 1,
    listing_id: 3,
    client_name: "Juan Dela Cruz",
    unit_code: "LA-0205",
    project_name: "Bailen",
    amount: 50000,
    payment_type: "reservation",
    payment_method: "cash",
    reference_id: "CASH-20260701-LA0205-0001",
    payment_date: "2026-07-01",
    verified_by: "Super Admin",
    verified_date: "2026-07-01",
    status: "verified",
    remarks: "Reservation fee paid.",
  },
  {
    payment_id: 2,
    listing_id: 3,
    client_name: "Juan Dela Cruz",
    unit_code: "LA-0205",
    project_name: "Bailen",
    amount: 97733.33,
    payment_type: "downpayment",
    payment_method: "bank_transfer",
    reference_id: "BDO-874612",
    payment_date: "2026-07-02",
    verified_by: null,
    verified_date: null,
    status: "pending",
    remarks: "For verification.",
  },
  {
    payment_id: 3,
    listing_id: 3,
    client_name: "Juan Dela Cruz",
    unit_code: "LA-0205",
    project_name: "Bailen",
    amount: 5000,
    payment_type: "advance_payment",
    payment_method: "online",
    reference_id: "MAYA-ADV-0003",
    payment_date: "2026-07-05",
    verified_by: "Admin",
    verified_date: "2026-07-05",
    status: "verified",
    remarks: "Advance payment. Should reduce duration, not monthly amount.",
  },
  {
    payment_id: 4,
    listing_id: 3,
    client_name: "Juan Dela Cruz",
    unit_code: "LA-0205",
    project_name: "Bailen",
    amount: 100000,
    payment_type: "balloon_payment",
    payment_method: "bank_transfer",
    reference_id: "BDO-BALLOON-0004",
    payment_date: "2026-12-22",
    verified_by: null,
    verified_date: null,
    status: "pending",
    remarks: "Final contracted balloon payment sample.",
  },
];

export const sampleBailenSOA: BailenSOARow[] = [
  {
    due_id: 1,
    listing_id: 3,
    due_date: "2026-07-01",
    description: "Reservation Fee",
    beginning_balance: 537625,
    due_amount: 50000,
    interest: 0,
    principal_paid: 50000,
    penalty: 0,
    date_paid: "2026-07-01",
    amount_paid: 50000,
    reference_id: "CASH-20260701-LA0205-0001",
    status: "paid",
    ending_balance: 487625,
  },
  {
    due_id: 2,
    listing_id: 3,
    due_date: "2026-07-22",
    description: "1st Downpayment",
    beginning_balance: 487625,
    due_amount: 97733.33,
    interest: 0,
    principal_paid: 0,
    penalty: 0,
    date_paid: null,
    amount_paid: 0,
    reference_id: null,
    status: "unpaid",
    ending_balance: 487625,
  },
  {
    due_id: 3,
    listing_id: 3,
    due_date: "2026-08-22",
    description: "2nd Downpayment",
    beginning_balance: 487625,
    due_amount: 97733.33,
    interest: 0,
    principal_paid: 0,
    penalty: 0,
    date_paid: null,
    amount_paid: 0,
    reference_id: null,
    status: "unpaid",
    ending_balance: 487625,
  },
];

export const sampleBailenCommissions: Commission[] = [
  {
    commission_id: 1,
    listing_id: 3,
    unit_code: "LA-0205",
    client_name: "Juan Dela Cruz",
    seller_name: "PARROCHO, JOSEPH E.",
    seller_role: "Manager",
    seller_group_id: 2,
    seller_group_name: "SARTE, JOHN CHRISTOPHER GROUP",
    tcp: 537625,
    pool_rate: 12,
    seller_rate: 3,
    gross_commission: 16128.75,
    eligible_amount: 6451.5,
    released_amount: 0,
    cash_advance_deduction: 0,
    net_remaining: 16128.75,
    next_release_stage: "20%",
    next_release_date: "2026-07-22",
    status: "eligible",
  },
];

export const cadastralLotNumberOptions = [
  { id: 1, label: "CAD-001" },
  { id: 2, label: "CAD-002" },
  { id: 3, label: "CAD-003" },
  { id: 4, label: "CAD-004" },
];
