import { createHash } from 'node:crypto';

const CLOUDINARY_ROOT_FOLDER = 'dc_prime';
const VALID_RESOURCE_TYPES = new Set(['image', 'raw', 'video']);

const cleanText = (value) => String(value ?? '').trim();

/**
 * Converts project/unit/document labels into the same folder-safe form used by
 * the client uploader (for example, "LA-0201" becomes "la_0201").
 */
export const sanitizeCloudinaryPathPart = (value, fallback = 'item') => {
  const clean = cleanText(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  return clean || fallback;
};

const splitCloudinaryPath = (value) => cleanText(value).split('/').filter(Boolean);

const joinCloudinaryPath = (segments) => segments.filter(Boolean).join('/');

const getUnitSegmentIndex = (segments) => {
  const rootIndex = segments.findIndex((segment) => segment === CLOUDINARY_ROOT_FOLDER);
  if (rootIndex >= 0 && segments.length > rootIndex + 2) return rootIndex + 2;
  return -1;
};

/**
 * Returns empty-folder cleanup targets from the deepest document folder up to
 * the Unit ID folder. Project and root folders are intentionally preserved.
 */
export const getCloudinaryFolderCleanupPaths = (folderPath) => {
  const segments = splitCloudinaryPath(folderPath);
  const unitIndex = getUnitSegmentIndex(segments);
  if (unitIndex < 0) return [];

  const paths = [];
  for (let length = segments.length; length >= unitIndex + 1; length -= 1) {
    paths.push(joinCloudinaryPath(segments.slice(0, length)));
  }
  return paths;
};

/**
 * Replaces the unit folder in paths generated by buildClientUnitDocumentFolder:
 * dc_prime/{project}/{unit}/{document}/documentimages.
 */
export const replaceCloudinaryUnitSegment = (pathValue, targetUnitId, previousUnitId = '') => {
  const original = cleanText(pathValue);
  if (!original) return '';

  const segments = splitCloudinaryPath(original);
  const targetUnitPart = sanitizeCloudinaryPathPart(targetUnitId, 'unit');
  const previousUnitPart = sanitizeCloudinaryPathPart(previousUnitId, '');
  const expectedIndex = getUnitSegmentIndex(segments);

  if (expectedIndex >= 0) {
    segments[expectedIndex] = targetUnitPart;
    return joinCloudinaryPath(segments);
  }

  if (previousUnitPart) {
    const previousIndex = segments.findIndex((segment) => segment === previousUnitPart);
    if (previousIndex >= 0) {
      segments[previousIndex] = targetUnitPart;
      return joinCloudinaryPath(segments);
    }
  }

  return original;
};

const stripCloudinaryVersion = (segments) => {
  if (segments[0] && /^v\d+$/.test(segments[0])) return segments.slice(1);
  return segments;
};

/**
 * Extracts a public ID from a standard Cloudinary delivery URL as a fallback
 * for older database entries that stored only the URL.
 */
export const getCloudinaryPublicIdFromUrl = (urlValue, resourceTypeValue = 'image') => {
  const urlText = cleanText(urlValue);
  if (!urlText || !urlText.includes('res.cloudinary.com')) return '';

  try {
    const url = new URL(urlText);
    const pathSegments = url.pathname.split('/').filter(Boolean);
    const uploadIndex = pathSegments.findIndex((segment) => ['upload', 'private', 'authenticated'].includes(segment));
    if (uploadIndex < 0 || uploadIndex >= pathSegments.length - 1) return '';

    const publicIdSegments = stripCloudinaryVersion(pathSegments.slice(uploadIndex + 1));
    if (!publicIdSegments.length) return '';

    const resourceType = VALID_RESOURCE_TYPES.has(cleanText(resourceTypeValue))
      ? cleanText(resourceTypeValue)
      : pathSegments[1] || 'image';

    if (resourceType !== 'raw') {
      const lastIndex = publicIdSegments.length - 1;
      publicIdSegments[lastIndex] = publicIdSegments[lastIndex].replace(/\.[^.\/]+$/, '');
    }

    return joinCloudinaryPath(publicIdSegments);
  } catch {
    return '';
  }
};

export const getCloudinaryResourceType = (entry = {}) => {
  const explicit = cleanText(
    entry.cloudinaryResourceType
      || entry.cloudinary_resource_type
      || entry.resourceType
      || entry.resource_type
  ).toLowerCase();

  if (VALID_RESOURCE_TYPES.has(explicit)) return explicit;

  const urlText = cleanText(entry.url || entry.secure_url || entry.fileUrl || entry.file_url);
  try {
    const url = new URL(urlText);
    const pathSegments = url.pathname.split('/').filter(Boolean);
    const candidate = pathSegments[1];
    return VALID_RESOURCE_TYPES.has(candidate) ? candidate : 'image';
  } catch {
    return 'image';
  }
};

const dirname = (pathValue) => {
  const segments = splitCloudinaryPath(pathValue);
  segments.pop();
  return joinCloudinaryPath(segments);
};

/**
 * Creates a move plan for one stored document asset. A plan is also generated
 * when the listing already has the new Unit ID but a legacy asset still points
 * at an older unit folder, allowing Save Changes to repair past mismatches.
 */
export const buildCloudinaryUnitAssetMove = (entry = {}, targetUnitId, previousUnitId = '') => {
  const resourceType = getCloudinaryResourceType(entry);
  const storedPublicId = cleanText(
    entry.cloudinaryPublicId
      || entry.cloudinary_public_id
      || entry.publicId
      || entry.public_id
  );
  const publicId = storedPublicId || getCloudinaryPublicIdFromUrl(
    entry.url || entry.secure_url || entry.fileUrl || entry.file_url,
    resourceType
  );

  if (!publicId) return null;

  const currentFolder = cleanText(
    entry.cloudinaryFolder
      || entry.cloudinary_folder
      || entry.folder
      || entry.cloudinaryAssetFolder
      || entry.cloudinary_asset_folder
      || entry.asset_folder
  ) || dirname(publicId);

  const targetPublicId = replaceCloudinaryUnitSegment(publicId, targetUnitId, previousUnitId);
  const targetFolder = replaceCloudinaryUnitSegment(currentFolder, targetUnitId, previousUnitId);

  if (!targetPublicId || targetPublicId === publicId) {
    // The public ID already points at the correct unit. Folder metadata may
    // still be repaired without making a Cloudinary rename request.
    if (targetFolder && targetFolder !== currentFolder) {
      return {
        needsRename: false,
        fromPublicId: publicId,
        toPublicId: publicId,
        fromFolder: currentFolder,
        toFolder: targetFolder,
        resourceType,
      };
    }
    return null;
  }

  return {
    needsRename: true,
    fromPublicId: publicId,
    toPublicId: targetPublicId,
    fromFolder: currentFolder,
    toFolder: targetFolder || dirname(targetPublicId),
    resourceType,
  };
};

const getCloudinaryConfig = () => ({
  cloudName: cleanText(process.env.CLOUDINARY_CLOUD_NAME),
  apiKey: cleanText(process.env.CLOUDINARY_API_KEY),
  apiSecret: cleanText(process.env.CLOUDINARY_API_SECRET),
  uploadPrefix: cleanText(process.env.CLOUDINARY_UPLOAD_PREFIX) || 'https://api.cloudinary.com',
});

export const assertCloudinaryManagementConfigured = () => {
  const config = getCloudinaryConfig();
  if (!config.cloudName || !config.apiKey || !config.apiSecret) {
    const error = new Error(
      'Cloudinary server credentials are required to move existing document folders. Configure CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET.'
    );
    error.statusCode = 503;
    throw error;
  }
  return config;
};

/**
 * Cloudinary signs management requests by sorting all request parameters,
 * joining them as key=value pairs, appending the API secret, and hashing SHA-1.
 */
export const createCloudinarySignature = (params, apiSecret) => {
  const canonical = Object.entries(params)
    .filter(([, value]) => value !== undefined && value !== null && value !== '')
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${value}`)
    .join('&');

  return createHash('sha1').update(`${canonical}${apiSecret}`).digest('hex');
};

const postSignedCloudinaryRequest = async ({ action, resourceType, params }) => {
  const config = assertCloudinaryManagementConfigured();
  const timestamp = Math.floor(Date.now() / 1000);
  const signedParams = { ...params, timestamp };
  const signature = createCloudinarySignature(signedParams, config.apiSecret);
  const body = new URLSearchParams();

  Object.entries(signedParams).forEach(([key, value]) => body.append(key, String(value)));
  body.append('api_key', config.apiKey);
  body.append('signature', signature);

  const safeResourceType = VALID_RESOURCE_TYPES.has(resourceType) ? resourceType : 'image';
  const response = await fetch(
    `${config.uploadPrefix.replace(/\/$/, '')}/v1_1/${encodeURIComponent(config.cloudName)}/${safeResourceType}/${action}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body,
    }
  );

  const result = await response.json().catch(() => null);
  if (!response.ok) {
    const message = result?.error?.message || result?.message || `Cloudinary ${action} request failed.`;
    const error = new Error(message);
    error.statusCode = response.status >= 400 && response.status < 500 ? 409 : 502;
    error.cloudinaryResponse = result;
    throw error;
  }

  return result || {};
};

export const renameCloudinaryAsset = async ({
  fromPublicId,
  toPublicId,
  resourceType = 'image',
  overwrite = false,
  invalidate = true,
}) => postSignedCloudinaryRequest({
  action: 'rename',
  resourceType,
  params: {
    from_public_id: fromPublicId,
    to_public_id: toPublicId,
    overwrite: overwrite ? 'true' : 'false',
    invalidate: invalidate ? 'true' : 'false',
  },
});

/**
 * Dynamic-folder Cloudinary environments separate the Media Library folder
 * from the public ID path. When the rename response exposes asset_folder, this
 * explicit call moves the asset's Media Library folder as well.
 */
export const moveCloudinaryDynamicAssetFolder = async ({ publicId, assetFolder, resourceType = 'image' }) => {
  if (!assetFolder) return null;
  return postSignedCloudinaryRequest({
    action: 'explicit',
    resourceType,
    params: {
      public_id: publicId,
      type: 'upload',
      asset_folder: assetFolder,
    },
  });
};


/**
 * Removes an empty Media Library folder after its assets were moved. Nested
 * folders are deleted separately by the caller, deepest first. A non-empty or
 * already-missing folder is reported without failing the listing update.
 */
export const deleteCloudinaryEmptyFolder = async ({ folder, skipBackup = true }) => {
  const folderPath = cleanText(folder);
  if (!folderPath) return { deleted: false, reason: 'missing_folder' };

  const config = assertCloudinaryManagementConfigured();
  const encodedFolder = folderPath.split('/').map((part) => encodeURIComponent(part)).join('/');
  const query = skipBackup ? '?skip_backup=true' : '';
  const credentials = Buffer.from(`${config.apiKey}:${config.apiSecret}`).toString('base64');
  const response = await fetch(
    `${config.uploadPrefix.replace(/\/$/, '')}/v1_1/${encodeURIComponent(config.cloudName)}/folders/${encodedFolder}${query}`,
    {
      method: 'DELETE',
      headers: { Authorization: `Basic ${credentials}` },
    }
  );

  const result = await response.json().catch(() => null);
  if (response.ok) return { deleted: true, folder: folderPath, result };

  const message = cleanText(result?.error?.message || result?.message || `Cloudinary folder deletion failed (${response.status}).`);
  const normalizedMessage = message.toLowerCase();

  if (response.status === 404 || normalizedMessage.includes('not found')) {
    return { deleted: false, folder: folderPath, reason: 'not_found' };
  }

  if (
    normalizedMessage.includes('not empty')
    || normalizedMessage.includes('contains assets')
    || normalizedMessage.includes('subfolder')
  ) {
    return { deleted: false, folder: folderPath, reason: 'not_empty', message };
  }

  const error = new Error(message);
  error.statusCode = response.status >= 400 && response.status < 500 ? 409 : 502;
  error.cloudinaryResponse = result;
  throw error;
};

export const applyCloudinaryMoveToEntry = (entry, move, renameResult = {}, folderResult = null) => {
  const nextUrl = renameResult.secure_url || renameResult.url || entry.url || entry.secure_url || entry.fileUrl || entry.file_url;
  const nextPublicId = renameResult.public_id || move.toPublicId;
  const nextAssetFolder = folderResult?.asset_folder || renameResult.asset_folder || move.toFolder;

  return {
    ...entry,
    url: nextUrl,
    cloudinaryPublicId: nextPublicId,
    cloudinaryResourceType: renameResult.resource_type || move.resourceType,
    cloudinaryFolder: move.toFolder,
    cloudinaryAssetFolder: nextAssetFolder || null,
  };
};
