import { useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import PrintPageShell from '../../components/Lot_Projects/ListingProfileComponents/Printouts/PrintPageShell'
import { useFetch } from '../../utils/useFetch'

const money = (value) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', minimumFractionDigits: 2 }).format(Number(value || 0))
const number = (value) => new Intl.NumberFormat('en-PH').format(Number(value || 0))
const dateOnly = (value) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(`${String(value).slice(0, 10)}T00:00:00`)) : '-'
const dateTime = (value) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-'

const PrintTable = ({ headers, rows, emptyText = 'No records.', widths = [] }) => (
  <table className="report-table mt-3 w-full table-fixed border-collapse text-[7px] leading-tight">
    {widths.length ? <colgroup>{widths.map((width, index) => <col key={index} style={{ width }} />)}</colgroup> : null}
    <thead><tr className="bg-slate-200">{headers.map((head) => <th key={head} className="border border-black px-1 py-1 text-left font-black uppercase">{head}</th>)}</tr></thead>
    <tbody>{rows.length ? rows : <tr><td colSpan={headers.length} className="border border-black px-2 py-5 text-center font-bold">{emptyText}</td></tr>}</tbody>
  </table>
)

const SectionPage = ({ title, subtitle, children }) => <section className="print-export-page mx-auto min-h-[210mm] w-[297mm] bg-white p-[8mm] text-black shadow-lg print:shadow-none"><header className="border-b-2 border-black pb-2"><p className="text-[9px] font-black uppercase tracking-[0.18em]">D&amp;C Prime Realty</p><div className="mt-1 flex items-end justify-between gap-4"><div><h1 className="text-lg font-black uppercase">{title}</h1>{subtitle ? <p className="mt-0.5 text-[9px] font-semibold">{subtitle}</p> : null}</div><p className="text-[8px] font-semibold">Confidential Management Report</p></div></header>{children}<footer className="mt-4 border-t border-black pt-2 text-[7px] font-semibold">D&amp;C Prime Realty — Confidential Financial Report</footer></section>

const ReportsPrintPage = () => {
  const params = new URLSearchParams(window.location.search)
  const query = params.toString()
  const from = params.get('from') || ''
  const to = params.get('to') || ''
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['system-report-print', query], queryFn: () => useFetch(`/projects/reports?${query}`), enabled: Boolean(from && to) })
  const payload = data?.data || {}
  const summary = payload.summary || {}
  const filters = payload.filters || {}
  const projectName = filters.projectId ? (payload.options?.projects || []).find((row) => Number(row.id) === Number(filters.projectId))?.name : 'All Projects'
  const sellerName = filters.sellerId ? (payload.options?.sellers || []).find((row) => Number(row.id) === Number(filters.sellerId))?.name : 'All Sellers'
  const generatedBy = payload.generated?.by?.name || 'Administrator'
  const generatedAt = payload.generated?.at ? dateTime(payload.generated.at) : dateTime(new Date().toISOString())

  useEffect(() => { document.title = `DC Prime Report ${from} to ${to}` }, [from, to])

  if (isLoading) return <PrintPageShell title="D&C Prime Reports" pageOrientation="landscape"><div className="p-6 text-sm font-semibold">Preparing report...</div></PrintPageShell>
  if (isError) return <PrintPageShell title="D&C Prime Reports" pageOrientation="landscape"><div className="p-6 text-sm font-semibold text-red-700">{error?.message || 'Failed to load report.'}</div></PrintPageShell>

  const reportSubtitle = `${from} to ${to} · ${projectName || 'All Projects'} · ${sellerName || 'All Sellers'}${filters.search ? ` · Search: ${filters.search}` : ''} · Generated by ${generatedBy} · ${generatedAt}`
  const metricRows = [
    ['Reservations', number(summary.reservationCount)], ['Contract Sales', money(summary.grossSales)], ['Collected in Range', money(summary.collectedInRange)], ['Cumulative Collected', money(summary.cumulativeCollected)],
    ['Outstanding', money(summary.outstandingAmount)], ['Cancellations', number(summary.cancelledCount)], ['Cancelled Value', money(summary.cancelledValue)], ['Refunded', money(summary.refundedAmount)],
    ['Discontinued / Retained', money(summary.discontinuedAmount)], ['Commission Generated', money(summary.commissionGenerated)], ['Commission Released', money(summary.commissionReleased)], ['Eligible — Not Released', money(summary.eligibleUnreleased)], ['Commission Remaining', money(summary.commissionRemaining)],
  ]

  return <PrintPageShell title="D&C Prime Management Report" pageOrientation="landscape">
    <style>{`@media print {.report-table thead{display:table-header-group}.report-table tr{break-inside:avoid;page-break-inside:avoid}}`}</style>

    <SectionPage title="Management Report — Executive Summary" subtitle={reportSubtitle}>
      <div className="mt-4 grid grid-cols-4 gap-2">{metricRows.map(([label,value]) => <div key={label} className="border border-black p-2"><p className="text-[7px] font-black uppercase text-slate-600">{label}</p><p className="mt-1 text-[11px] font-black">{value}</p></div>)}</div>
      <h2 className="mt-5 text-[10px] font-black uppercase">Project Breakdown</h2>
      <PrintTable headers={['Project','Reservations','Cancelled','Collected in Range','Cumulative Collected','Outstanding','Refunded','Commission Released','Eligible Unreleased']} rows={(payload.projectBreakdown || []).map((row) => <tr key={row.projectId}><td className="border border-black px-1 py-1 font-black">{row.project}</td><td className="border border-black px-1 py-1">{number(row.reservations)}</td><td className="border border-black px-1 py-1">{number(row.cancelled)}</td><td className="border border-black px-1 py-1">{money(row.collectedInRange)}</td><td className="border border-black px-1 py-1">{money(row.cumulativeCollected)}</td><td className="border border-black px-1 py-1">{money(row.outstanding)}</td><td className="border border-black px-1 py-1">{money(row.refunded)}</td><td className="border border-black px-1 py-1">{money(row.commissionReleased)}</td><td className="border border-black px-1 py-1">{money(row.eligibleUnreleased)}</td></tr>)} />
      <h2 className="mt-5 text-[10px] font-black uppercase">Seller Performance</h2>
      <PrintTable headers={['Seller','Group','Reservations','Sales Amount','Collected in Range','Gross Commission','Released','Eligible Unreleased']} rows={(payload.sellerPerformance || []).map((row,index) => <tr key={`${row.sellerId}-${index}`}><td className="border border-black px-1 py-1 font-black">{row.seller}</td><td className="border border-black px-1 py-1">{row.sellerGroup}</td><td className="border border-black px-1 py-1">{number(row.reservations)}</td><td className="border border-black px-1 py-1">{money(row.salesAmount)}</td><td className="border border-black px-1 py-1">{money(row.collectedInRange)}</td><td className="border border-black px-1 py-1">{money(row.grossCommission)}</td><td className="border border-black px-1 py-1">{money(row.releasedCommission)}</td><td className="border border-black px-1 py-1">{money(row.eligibleUnreleased)}</td></tr>)} />
    </SectionPage>

    <SectionPage title="Reservations & Sales" subtitle={reportSubtitle}>
      <PrintTable headers={['Reserved','Project','Unit','Buyer','Account','Seller','Group','Mode','TCP','Status']} rows={(payload.reservations || []).map((row) => <tr key={row.id}><td className="border border-black px-1 py-1">{dateTime(row.reservationDate)}</td><td className="border border-black px-1 py-1">{row.project}</td><td className="border border-black px-1 py-1 font-black">{row.unit}</td><td className="border border-black px-1 py-1">{row.buyer}</td><td className="border border-black px-1 py-1">{row.accountReference}</td><td className="border border-black px-1 py-1">{row.seller}</td><td className="border border-black px-1 py-1">{row.sellerGroup}</td><td className="border border-black px-1 py-1">{row.modeOfPayment}</td><td className="border border-black px-1 py-1">{money(row.tcp)}</td><td className="border border-black px-1 py-1">{row.reservationStatus}</td></tr>)} />
    </SectionPage>

    <SectionPage title="Payments & Outstanding Accounts" subtitle={reportSubtitle}>
      <h2 className="mt-3 text-[10px] font-black uppercase">Payments in Selected Range</h2>
      <PrintTable headers={['Date','Project','Unit','Buyer','Account','Type','Method','Bank','Reference','Amount','Status','Verified By']} rows={(payload.payments || []).map((row) => <tr key={row.id}><td className="border border-black px-1 py-1">{dateOnly(row.paymentDate)}</td><td className="border border-black px-1 py-1">{row.project}</td><td className="border border-black px-1 py-1">{row.unit}</td><td className="border border-black px-1 py-1">{row.buyer}</td><td className="border border-black px-1 py-1">{row.accountReference}</td><td className="border border-black px-1 py-1">{row.type}</td><td className="border border-black px-1 py-1">{row.method}</td><td className="border border-black px-1 py-1">{row.bank || '-'}</td><td className="border border-black px-1 py-1">{row.reference || '-'}</td><td className="border border-black px-1 py-1 font-black">{money(row.amount)}</td><td className="border border-black px-1 py-1">{row.status}</td><td className="border border-black px-1 py-1">{row.verifiedBy}</td></tr>)} />
      <h2 className="mt-5 text-[10px] font-black uppercase">Outstanding Accounts as of {to}</h2>
      <PrintTable headers={['Project','Unit','Buyer','Account','Seller','Contract Value','Cumulative Paid','Outstanding']} rows={(payload.outstandingAccounts || []).map((row) => <tr key={row.accountId}><td className="border border-black px-1 py-1">{row.project}</td><td className="border border-black px-1 py-1">{row.unit}</td><td className="border border-black px-1 py-1">{row.buyer}</td><td className="border border-black px-1 py-1">{row.accountReference}</td><td className="border border-black px-1 py-1">{row.seller}</td><td className="border border-black px-1 py-1">{money(row.contractValue)}</td><td className="border border-black px-1 py-1">{money(row.cumulativePaid)}</td><td className="border border-black px-1 py-1 font-black">{money(row.outstanding)}</td></tr>)} />
    </SectionPage>

    <SectionPage title="Cancellations & Refunds" subtitle={reportSubtitle}>
      <PrintTable headers={['Cancelled','Project','Unit','Buyer','Account','Type','Cancelled Value','Cash Collected','Refund','Discontinued','Refund Date','Reference','Reason','Cancelled By']} rows={(payload.cancellations || []).map((row) => <tr key={row.id}><td className="border border-black px-1 py-1">{dateTime(row.cancellationDate)}</td><td className="border border-black px-1 py-1">{row.project}</td><td className="border border-black px-1 py-1">{row.unit}</td><td className="border border-black px-1 py-1">{row.buyer}</td><td className="border border-black px-1 py-1">{row.accountReference}</td><td className="border border-black px-1 py-1">{row.cancellationType}</td><td className="border border-black px-1 py-1">{money(row.cancelledValue)}</td><td className="border border-black px-1 py-1">{money(row.cashCollected)}</td><td className="border border-black px-1 py-1">{money(row.refundAmount)}</td><td className="border border-black px-1 py-1">{money(row.discontinuedAmount)}</td><td className="border border-black px-1 py-1">{dateOnly(row.refundDate)}</td><td className="border border-black px-1 py-1">{row.refundReference || '-'}</td><td className="border border-black px-1 py-1 whitespace-normal">{row.reason || '-'}</td><td className="border border-black px-1 py-1">{row.cancelledBy}</td></tr>)} />
    </SectionPage>

    <SectionPage title="Commission Details" subtitle={`${reportSubtitle} · Released uses actual release date`}>
      <PrintTable headers={['Project','Unit','Buyer','Recipient','Role','Group','Stage','Trigger','Release %','Net Amount','Payment %','Status','Scheduled','Actual Release','Released By']} rows={(payload.releases || []).map((row) => <tr key={row.id}><td className="border border-black px-1 py-1">{row.project}</td><td className="border border-black px-1 py-1">{row.unit}</td><td className="border border-black px-1 py-1">{row.buyer}</td><td className="border border-black px-1 py-1 font-black">{row.seller}</td><td className="border border-black px-1 py-1">{row.role}</td><td className="border border-black px-1 py-1">{row.sellerGroup}</td><td className="border border-black px-1 py-1">{row.stage}</td><td className="border border-black px-1 py-1">{row.triggerPercent}%</td><td className="border border-black px-1 py-1">{row.releasePercent}%</td><td className="border border-black px-1 py-1 font-black">{money(row.netAmount)}</td><td className="border border-black px-1 py-1">{row.paymentPercent}%</td><td className="border border-black px-1 py-1">{row.eligibleAsOf && row.status !== 'Released' ? 'Eligible as of end date' : row.status}</td><td className="border border-black px-1 py-1">{dateOnly(row.scheduledReleaseDate)}</td><td className="border border-black px-1 py-1">{dateOnly(row.actualReleaseDate)}</td><td className="border border-black px-1 py-1">{row.releasedBy}</td></tr>)} />
    </SectionPage>
  </PrintPageShell>
}

export default ReportsPrintPage

