import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const readProjectFile = (relativePath) =>
  readFile(new URL(`../../${relativePath}`, import.meta.url), 'utf8');

test('user creation no longer exposes a temporary password field', async () => {
  const source = await readProjectFile('client/src/components/System/userComponents/CreateUserModal.jsx');

  assert.doesNotMatch(source, /form\.password/);
  assert.doesNotMatch(source, /Temporary Password \*/);
  assert.match(source, /Secure Login Setup/);
  assert.match(source, /secure temporary password will be generated by the server and sent to the user.*email/i);
});

test('credential regeneration is offered only for Admin and Super Admin rows', async () => {
  const source = await readProjectFile('client/src/pages/System/Users.jsx');

  assert.match(source, /const canResetUserPassword = \(user\) => canResetPasswords && \['admin', 'super_admin'\]\.includes\(user\?\.role\)/);
  assert.match(source, /Resend Login Credentials\?/);
  assert.match(source, /Generate & Send Credentials/);
  assert.match(source, /\{canResetUserPassword\(user\) \? <button[\s\S]*Credentials/);
});

