import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const readProjectFile = (relativePath) =>
  readFile(new URL(`../../${relativePath}`, import.meta.url), 'utf8');

test('user creation no longer exposes a temporary password field', async () => {
  const source = await readProjectFile('client/src/components/System/userComponents/CreateUserModal.jsx');

  assert.doesNotMatch(source, /form\.password/);
  assert.doesNotMatch(source, /Temporary Password \*/);
  assert.match(source, /Secure Login Setup/);
  assert.match(source, /secure temporary password will be generated by the server and sent to the user.*email/i);
});

test('User Management does not expose credential regeneration because password recovery is handled from login', async () => {
  const source = await readProjectFile('client/src/pages/System/Users.jsx');

  assert.doesNotMatch(source, /Resend Login Credentials\?/);
  assert.doesNotMatch(source, /Generate & Send Credentials/);
  assert.doesNotMatch(source, />Credentials<\/button>/);
  assert.doesNotMatch(source, /resetPasswordMutation/);
  assert.doesNotMatch(source, /\/user\/resetPassword\//);
});

